# Message routes
MESSAGE_CREATE = "MESSAGE_CREATE"
MESSAGE_LIST = "MESSAGE_LIST"
MESSAGE_FETCH = "MESSAGE_FETCH"
MESSAGE_DELETE = "MESSAGE_DELETE"
MESSAGE_BULK_DELETE = "MESSAGE_BULK_DELETE"
MESSAGE_EDIT = "MESSAGE_EDIT"